/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DeveloperService } from "../developer.service";
import { DeveloperCreateInput } from "./DeveloperCreateInput";
import { Developer } from "./Developer";
import { DeveloperFindManyArgs } from "./DeveloperFindManyArgs";
import { DeveloperWhereUniqueInput } from "./DeveloperWhereUniqueInput";
import { DeveloperUpdateInput } from "./DeveloperUpdateInput";
import { ApiUsageFindManyArgs } from "../../apiUsage/base/ApiUsageFindManyArgs";
import { ApiUsage } from "../../apiUsage/base/ApiUsage";
import { ApiUsageWhereUniqueInput } from "../../apiUsage/base/ApiUsageWhereUniqueInput";
import { LicenseAgreementFindManyArgs } from "../../licenseAgreement/base/LicenseAgreementFindManyArgs";
import { LicenseAgreement } from "../../licenseAgreement/base/LicenseAgreement";
import { LicenseAgreementWhereUniqueInput } from "../../licenseAgreement/base/LicenseAgreementWhereUniqueInput";

export class DeveloperControllerBase {
  constructor(protected readonly service: DeveloperService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Developer })
  async createDeveloper(
    @common.Body() data: DeveloperCreateInput
  ): Promise<Developer> {
    return await this.service.createDeveloper({
      data: data,
      select: {
        apiKey: true,
        createdAt: true,
        email: true,
        id: true,
        name: true,
        subscriptionPlan: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Developer] })
  @ApiNestedQuery(DeveloperFindManyArgs)
  async developers(@common.Req() request: Request): Promise<Developer[]> {
    const args = plainToClass(DeveloperFindManyArgs, request.query);
    return this.service.developers({
      ...args,
      select: {
        apiKey: true,
        createdAt: true,
        email: true,
        id: true,
        name: true,
        subscriptionPlan: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Developer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async developer(
    @common.Param() params: DeveloperWhereUniqueInput
  ): Promise<Developer | null> {
    const result = await this.service.developer({
      where: params,
      select: {
        apiKey: true,
        createdAt: true,
        email: true,
        id: true,
        name: true,
        subscriptionPlan: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Developer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDeveloper(
    @common.Param() params: DeveloperWhereUniqueInput,
    @common.Body() data: DeveloperUpdateInput
  ): Promise<Developer | null> {
    try {
      return await this.service.updateDeveloper({
        where: params,
        data: data,
        select: {
          apiKey: true,
          createdAt: true,
          email: true,
          id: true,
          name: true,
          subscriptionPlan: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Developer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDeveloper(
    @common.Param() params: DeveloperWhereUniqueInput
  ): Promise<Developer | null> {
    try {
      return await this.service.deleteDeveloper({
        where: params,
        select: {
          apiKey: true,
          createdAt: true,
          email: true,
          id: true,
          name: true,
          subscriptionPlan: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/apiUsages")
  @ApiNestedQuery(ApiUsageFindManyArgs)
  async findApiUsages(
    @common.Req() request: Request,
    @common.Param() params: DeveloperWhereUniqueInput
  ): Promise<ApiUsage[]> {
    const query = plainToClass(ApiUsageFindManyArgs, request.query);
    const results = await this.service.findApiUsages(params.id, {
      ...query,
      select: {
        createdAt: true,

        developer: {
          select: {
            id: true,
          },
        },

        endpoint: true,
        id: true,
        requestTimestamp: true,
        responseStatus: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/apiUsages")
  async connectApiUsages(
    @common.Param() params: DeveloperWhereUniqueInput,
    @common.Body() body: ApiUsageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      apiUsages: {
        connect: body,
      },
    };
    await this.service.updateDeveloper({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/apiUsages")
  async updateApiUsages(
    @common.Param() params: DeveloperWhereUniqueInput,
    @common.Body() body: ApiUsageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      apiUsages: {
        set: body,
      },
    };
    await this.service.updateDeveloper({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/apiUsages")
  async disconnectApiUsages(
    @common.Param() params: DeveloperWhereUniqueInput,
    @common.Body() body: ApiUsageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      apiUsages: {
        disconnect: body,
      },
    };
    await this.service.updateDeveloper({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/licenseAgreements")
  @ApiNestedQuery(LicenseAgreementFindManyArgs)
  async findLicenseAgreements(
    @common.Req() request: Request,
    @common.Param() params: DeveloperWhereUniqueInput
  ): Promise<LicenseAgreement[]> {
    const query = plainToClass(LicenseAgreementFindManyArgs, request.query);
    const results = await this.service.findLicenseAgreements(params.id, {
      ...query,
      select: {
        createdAt: true,

        developer: {
          select: {
            id: true,
          },
        },

        endDate: true,
        id: true,
        startDate: true,
        terms: true,
        track: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/licenseAgreements")
  async connectLicenseAgreements(
    @common.Param() params: DeveloperWhereUniqueInput,
    @common.Body() body: LicenseAgreementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      licenseAgreements: {
        connect: body,
      },
    };
    await this.service.updateDeveloper({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/licenseAgreements")
  async updateLicenseAgreements(
    @common.Param() params: DeveloperWhereUniqueInput,
    @common.Body() body: LicenseAgreementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      licenseAgreements: {
        set: body,
      },
    };
    await this.service.updateDeveloper({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/licenseAgreements")
  async disconnectLicenseAgreements(
    @common.Param() params: DeveloperWhereUniqueInput,
    @common.Body() body: LicenseAgreementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      licenseAgreements: {
        disconnect: body,
      },
    };
    await this.service.updateDeveloper({
      where: params,
      data,
      select: { id: true },
    });
  }
}
