/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { ApiUsageListRelationFilter } from "../../apiUsage/base/ApiUsageListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { LicenseAgreementListRelationFilter } from "../../licenseAgreement/base/LicenseAgreementListRelationFilter";

@InputType()
class DeveloperWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  apiKey?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ApiUsageListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ApiUsageListRelationFilter)
  @IsOptional()
  @Field(() => ApiUsageListRelationFilter, {
    nullable: true,
  })
  apiUsages?: ApiUsageListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => LicenseAgreementListRelationFilter,
  })
  @ValidateNested()
  @Type(() => LicenseAgreementListRelationFilter)
  @IsOptional()
  @Field(() => LicenseAgreementListRelationFilter, {
    nullable: true,
  })
  licenseAgreements?: LicenseAgreementListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  subscriptionPlan?: StringNullableFilter;
}

export { DeveloperWhereInput as DeveloperWhereInput };
